### ISSUE TITLE
Question on SSR deployment using AWS Lambda on Netlify

### ISSUE THREAD

**Issue by pythonpen** [jiangfengming/svelte-vite-ssr#3]
Hi,
This is a very impressive repo with rich features! Great!

Writing to know  how this repo can be deployed in a SSR way using AWS Lambda and Netlify. Appreciate any pointers towards this. Thanks!

**Comment by jiangfengming** [comment]
1. Connect to Git provider
2. Pick a repository
3. Hit the "Deploy site" button directly. It's done. Thanks to the [netlify.toml](https://github.com/jiangfengming/svelte-vite-ssr/blob/main/netlify.toml) file in the repo, you don't need to set anything.

![app netlify com_start_repos_jiangfengming%2Fsvs-test](https://user-images.githubusercontent.com/11750532/177313213-b657fab4-a37c-4fe7-8ac7-b436e94f218b.png)

**Comment by pythonpen** [comment]
Great, Thank you for the response.
