### ISSUE TITLE
How do i remove __SSR__ from the rendered html

### ISSUE THREAD

**Issue by sulaimon-abiola** [jiangfengming/svelte-vite-ssr#4]
Hello

I would like to commend your efforts with the this package, it is so helpfull

Please how do i remove  the __SSR__ from the rendered html, am not sure about its use, but I like to remove it

**Comment by jiangfengming** [comment]
Hi @Sulaimon-Abiola ,

Thanks for the feedback! About removing SSR from the HTML, do you mean you only want client-side rendering for a single-page application?
